name: 'Ollama Code Review'
description: 'Request a code review from the Ollama server for a GitHub pull request.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code-review'
  color: 'blue'
