name: Ollama Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  request-review:
    runs-on: elice

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Ollama Code Review
      uses: ./
      with:
        OLLAMA_API_URL: ${{ secrets.OLLAMA_API_URL }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        OWNER: poseidonos
        REPO: pos-essential-orchestrator
        PR_NUMBER: 744
        CUSTOM_PROMPT: 'Especially recommend code location of logger.info(), logger.debug() code, please specify filename and line number for each log statement.'
        RESPONSE_LANGUAGE: 'Korean'
        MODEL: 'llama3.3'