name: Ollama Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  request-review:
    runs-on: elice

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Ollama Code Review
      uses: ./
      with:
        OLLAMA_API_URL: ${{ secrets.OLLAMA_API_URL }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        CUSTOM_PROMPT: ''
        RESPONSE_LANGUAGE: 'Korean'
        MODEL: 'qwen2.5-coder:32b'